services:
  mailhog:
    image: mailhog/mailhog
    restart: no
    ports:
      - '1025:1025'
      - '8025:8025'

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: no
    environment:
      PMA_HOST: mysql
    ports:
      - '9000:80'

  hate-speech-api:
    build:
      context: ./ai/hate-speech-detector
      dockerfile: Dockerfile
    ports:
      - '6000:6000'
    environment:
      - PORT=6000
    restart: unless-stopped

  ocr-api:
    build:
      context: ./ai/ocr-model
      dockerfile: Dockerfile
    ports:
    - '5000:5000'  # host:container
    environment:
      - PORT=5000    # Set the container port
    restart: unless-stopped

volumes:
  mysql_data:
